### ISSUE TITLE
issue with scoop

### ISSUE THREAD

**Issue by obar1** [radulucut/cleed#1]
tried as readme

https://github.com/radulucut/cleed/blob/e888bca2934d633716767a7f5c97f1146678b648/README.md?plain=1#L21

> cmd line as admin 
![image](https://github.com/user-attachments/assets/4dbc7202-f581-4718-85a5-c822a037b3ef)

**Comment by radulucut** [comment]
yeah, my bad
```
scoop bucket add cleed https://github.com/radulucut/scoop-cleed
scoop install cleed
```

thanks for raising this
