### ISSUE TITLE
Fix title colors

### ISSUE THREAD

**Issue by yonas** [radulucut/cleed#2]
Titles on the left are not visible. I see them only when highlighting the text.

![Screenshot from 2024-08-16 12-48-15](https://github.com/user-attachments/assets/ddacee20-7142-455f-9135-499e69534710)

**Comment by radulucut** [comment]
Thank you for raising this.

You can now map colors to avoid dealing with this issue by using `cleed config --map-colors` (since v0.1.6).

Please check https://github.com/radulucut/cleed?tab=readme-ov-file#configuration for more information
